[window]
decorations = "None"
opacity = 0.92
blur = true
padding = { x = 10, y = 10 }

[font]
normal = { family = "MesloLGL Nerd Font", style = "Regular" }
bold = { family = "MesloLGL Nerd Font", style = "Bold" }
italic = { family = "MesloLGL Nerd Font", style = "Italic" }
bold_italic = { family = "MesloLGL Nerd Font", style = "Bold Italic" }
size = 11.5
offset = { x = 1 }
